/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions.route'
import { Route as ServicesRouteImport } from './routes/services.route'
import { Route as ProjectsRouteImport } from './routes/projects.route'
import { Route as ProductsRouteImport } from './routes/products.route'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy.route'
import { Route as CareersRouteImport } from './routes/careers.route'
import { Route as BlogRouteImport } from './routes/blog.route'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard.route'
import { Route as AboutRouteImport } from './routes/about.route'
import { Route as IndexRouteImport } from './routes/index.route'
import { Route as BlogIndexRouteImport } from './routes/blog/index.route'
import { Route as BlogWoocommerceVsShopifyRouteImport } from './routes/blog/woocommerce-vs-shopify.route'
import { Route as BlogWebsiteBusinessNeeds2025RouteImport } from './routes/blog/website-business-needs-2025.route'
import { Route as BlogWebDevelopmentTrends2025RouteImport } from './routes/blog/web-development-trends-2025.route'
import { Route as BlogAiTransformingWebsitesRouteImport } from './routes/blog/ai-transforming-websites.route'

// Create/Update Routes

const TermsAndConditionsRouteRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRoute,
} as any)

const ServicesRouteRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsRouteRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRoute,
} as any)

const ProductsRouteRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRoute,
} as any)

const PrivacyPolicyRouteRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRoute,
} as any)

const CareersRouteRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRoute,
} as any)

const BlogRouteRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRoute,
} as any)

const AdminDashboardRouteRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AboutRouteRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRouteRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BlogIndexRouteRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRouteRoute,
} as any)

const BlogWoocommerceVsShopifyRouteRoute =
  BlogWoocommerceVsShopifyRouteImport.update({
    id: '/woocommerce-vs-shopify',
    path: '/woocommerce-vs-shopify',
    getParentRoute: () => BlogRouteRoute,
  } as any)

const BlogWebsiteBusinessNeeds2025RouteRoute =
  BlogWebsiteBusinessNeeds2025RouteImport.update({
    id: '/website-business-needs-2025',
    path: '/website-business-needs-2025',
    getParentRoute: () => BlogRouteRoute,
  } as any)

const BlogWebDevelopmentTrends2025RouteRoute =
  BlogWebDevelopmentTrends2025RouteImport.update({
    id: '/web-development-trends-2025',
    path: '/web-development-trends-2025',
    getParentRoute: () => BlogRouteRoute,
  } as any)

const BlogAiTransformingWebsitesRouteRoute =
  BlogAiTransformingWebsitesRouteImport.update({
    id: '/ai-transforming-websites',
    path: '/ai-transforming-websites',
    getParentRoute: () => BlogRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRoute
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRoute
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRoute
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRoute
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRoute
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRoute
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRoute
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRoute
    }
    '/blog/ai-transforming-websites': {
      id: '/blog/ai-transforming-websites'
      path: '/ai-transforming-websites'
      fullPath: '/blog/ai-transforming-websites'
      preLoaderRoute: typeof BlogAiTransformingWebsitesRouteImport
      parentRoute: typeof BlogRouteImport
    }
    '/blog/web-development-trends-2025': {
      id: '/blog/web-development-trends-2025'
      path: '/web-development-trends-2025'
      fullPath: '/blog/web-development-trends-2025'
      preLoaderRoute: typeof BlogWebDevelopmentTrends2025RouteImport
      parentRoute: typeof BlogRouteImport
    }
    '/blog/website-business-needs-2025': {
      id: '/blog/website-business-needs-2025'
      path: '/website-business-needs-2025'
      fullPath: '/blog/website-business-needs-2025'
      preLoaderRoute: typeof BlogWebsiteBusinessNeeds2025RouteImport
      parentRoute: typeof BlogRouteImport
    }
    '/blog/woocommerce-vs-shopify': {
      id: '/blog/woocommerce-vs-shopify'
      path: '/woocommerce-vs-shopify'
      fullPath: '/blog/woocommerce-vs-shopify'
      preLoaderRoute: typeof BlogWoocommerceVsShopifyRouteImport
      parentRoute: typeof BlogRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRouteImport
    }
  }
}

// Create and export the route tree

interface BlogRouteRouteChildren {
  BlogAiTransformingWebsitesRouteRoute: typeof BlogAiTransformingWebsitesRouteRoute
  BlogWebDevelopmentTrends2025RouteRoute: typeof BlogWebDevelopmentTrends2025RouteRoute
  BlogWebsiteBusinessNeeds2025RouteRoute: typeof BlogWebsiteBusinessNeeds2025RouteRoute
  BlogWoocommerceVsShopifyRouteRoute: typeof BlogWoocommerceVsShopifyRouteRoute
  BlogIndexRouteRoute: typeof BlogIndexRouteRoute
}

const BlogRouteRouteChildren: BlogRouteRouteChildren = {
  BlogAiTransformingWebsitesRouteRoute: BlogAiTransformingWebsitesRouteRoute,
  BlogWebDevelopmentTrends2025RouteRoute:
    BlogWebDevelopmentTrends2025RouteRoute,
  BlogWebsiteBusinessNeeds2025RouteRoute:
    BlogWebsiteBusinessNeeds2025RouteRoute,
  BlogWoocommerceVsShopifyRouteRoute: BlogWoocommerceVsShopifyRouteRoute,
  BlogIndexRouteRoute: BlogIndexRouteRoute,
}

const BlogRouteRouteWithChildren = BlogRouteRoute._addFileChildren(
  BlogRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/about': typeof AboutRouteRoute
  '/admin-dashboard': typeof AdminDashboardRouteRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/careers': typeof CareersRouteRoute
  '/privacy-policy': typeof PrivacyPolicyRouteRoute
  '/products': typeof ProductsRouteRoute
  '/projects': typeof ProjectsRouteRoute
  '/services': typeof ServicesRouteRoute
  '/terms-and-conditions': typeof TermsAndConditionsRouteRoute
  '/blog/ai-transforming-websites': typeof BlogAiTransformingWebsitesRouteRoute
  '/blog/web-development-trends-2025': typeof BlogWebDevelopmentTrends2025RouteRoute
  '/blog/website-business-needs-2025': typeof BlogWebsiteBusinessNeeds2025RouteRoute
  '/blog/woocommerce-vs-shopify': typeof BlogWoocommerceVsShopifyRouteRoute
  '/blog/': typeof BlogIndexRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/about': typeof AboutRouteRoute
  '/admin-dashboard': typeof AdminDashboardRouteRoute
  '/careers': typeof CareersRouteRoute
  '/privacy-policy': typeof PrivacyPolicyRouteRoute
  '/products': typeof ProductsRouteRoute
  '/projects': typeof ProjectsRouteRoute
  '/services': typeof ServicesRouteRoute
  '/terms-and-conditions': typeof TermsAndConditionsRouteRoute
  '/blog/ai-transforming-websites': typeof BlogAiTransformingWebsitesRouteRoute
  '/blog/web-development-trends-2025': typeof BlogWebDevelopmentTrends2025RouteRoute
  '/blog/website-business-needs-2025': typeof BlogWebsiteBusinessNeeds2025RouteRoute
  '/blog/woocommerce-vs-shopify': typeof BlogWoocommerceVsShopifyRouteRoute
  '/blog': typeof BlogIndexRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRouteRoute
  '/about': typeof AboutRouteRoute
  '/admin-dashboard': typeof AdminDashboardRouteRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/careers': typeof CareersRouteRoute
  '/privacy-policy': typeof PrivacyPolicyRouteRoute
  '/products': typeof ProductsRouteRoute
  '/projects': typeof ProjectsRouteRoute
  '/services': typeof ServicesRouteRoute
  '/terms-and-conditions': typeof TermsAndConditionsRouteRoute
  '/blog/ai-transforming-websites': typeof BlogAiTransformingWebsitesRouteRoute
  '/blog/web-development-trends-2025': typeof BlogWebDevelopmentTrends2025RouteRoute
  '/blog/website-business-needs-2025': typeof BlogWebsiteBusinessNeeds2025RouteRoute
  '/blog/woocommerce-vs-shopify': typeof BlogWoocommerceVsShopifyRouteRoute
  '/blog/': typeof BlogIndexRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin-dashboard'
    | '/blog'
    | '/careers'
    | '/privacy-policy'
    | '/products'
    | '/projects'
    | '/services'
    | '/terms-and-conditions'
    | '/blog/ai-transforming-websites'
    | '/blog/web-development-trends-2025'
    | '/blog/website-business-needs-2025'
    | '/blog/woocommerce-vs-shopify'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-dashboard'
    | '/careers'
    | '/privacy-policy'
    | '/products'
    | '/projects'
    | '/services'
    | '/terms-and-conditions'
    | '/blog/ai-transforming-websites'
    | '/blog/web-development-trends-2025'
    | '/blog/website-business-needs-2025'
    | '/blog/woocommerce-vs-shopify'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin-dashboard'
    | '/blog'
    | '/careers'
    | '/privacy-policy'
    | '/products'
    | '/projects'
    | '/services'
    | '/terms-and-conditions'
    | '/blog/ai-transforming-websites'
    | '/blog/web-development-trends-2025'
    | '/blog/website-business-needs-2025'
    | '/blog/woocommerce-vs-shopify'
    | '/blog/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  AboutRouteRoute: typeof AboutRouteRoute
  AdminDashboardRouteRoute: typeof AdminDashboardRouteRoute
  BlogRouteRoute: typeof BlogRouteRouteWithChildren
  CareersRouteRoute: typeof CareersRouteRoute
  PrivacyPolicyRouteRoute: typeof PrivacyPolicyRouteRoute
  ProductsRouteRoute: typeof ProductsRouteRoute
  ProjectsRouteRoute: typeof ProjectsRouteRoute
  ServicesRouteRoute: typeof ServicesRouteRoute
  TermsAndConditionsRouteRoute: typeof TermsAndConditionsRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  AboutRouteRoute: AboutRouteRoute,
  AdminDashboardRouteRoute: AdminDashboardRouteRoute,
  BlogRouteRoute: BlogRouteRouteWithChildren,
  CareersRouteRoute: CareersRouteRoute,
  PrivacyPolicyRouteRoute: PrivacyPolicyRouteRoute,
  ProductsRouteRoute: ProductsRouteRoute,
  ProjectsRouteRoute: ProjectsRouteRoute,
  ServicesRouteRoute: ServicesRouteRoute,
  TermsAndConditionsRouteRoute: TermsAndConditionsRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/admin-dashboard",
        "/blog",
        "/careers",
        "/privacy-policy",
        "/products",
        "/projects",
        "/services",
        "/terms-and-conditions"
      ]
    },
    "/": {
      "filePath": "index.route.tsx"
    },
    "/about": {
      "filePath": "about.route.tsx"
    },
    "/admin-dashboard": {
      "filePath": "admin-dashboard.route.tsx"
    },
    "/blog": {
      "filePath": "blog.route.tsx",
      "children": [
        "/blog/ai-transforming-websites",
        "/blog/web-development-trends-2025",
        "/blog/website-business-needs-2025",
        "/blog/woocommerce-vs-shopify",
        "/blog/"
      ]
    },
    "/careers": {
      "filePath": "careers.route.tsx"
    },
    "/privacy-policy": {
      "filePath": "privacy-policy.route.tsx"
    },
    "/products": {
      "filePath": "products.route.tsx"
    },
    "/projects": {
      "filePath": "projects.route.tsx"
    },
    "/services": {
      "filePath": "services.route.tsx"
    },
    "/terms-and-conditions": {
      "filePath": "terms-and-conditions.route.tsx"
    },
    "/blog/ai-transforming-websites": {
      "filePath": "blog/ai-transforming-websites.route.tsx",
      "parent": "/blog"
    },
    "/blog/web-development-trends-2025": {
      "filePath": "blog/web-development-trends-2025.route.tsx",
      "parent": "/blog"
    },
    "/blog/website-business-needs-2025": {
      "filePath": "blog/website-business-needs-2025.route.tsx",
      "parent": "/blog"
    },
    "/blog/woocommerce-vs-shopify": {
      "filePath": "blog/woocommerce-vs-shopify.route.tsx",
      "parent": "/blog"
    },
    "/blog/": {
      "filePath": "blog/index.route.tsx",
      "parent": "/blog"
    }
  }
}
ROUTE_MANIFEST_END */
